### ISSUE TITLE
/phpmyBugs/index.php?project=default&page=issues: Fatal error: Uncaught Error: Undefined class constant 'W_CURRENT' in \phpmyBugs\classes\Pager.class.php:41 Stack trace: #0 \phpmyBugs\pages\issues.php(144): Pager->get(Array, Object(Url), Array, 12) #1 \phpmyBugs\classes\Page.class.php(48): include('C:\\xampp\\htdocs...') #2 \phpmyBugs\index.php(382): Page->load('issues') #3 {main} thrown in \phpmyBugs\classes\Pager.class.php on line 41 with RU language.

### ISSUE THREAD

**Issue by dineshkummarc** [dineshkummarc/phpmyBugs#38]
/phpmyBugs/index.php?project=default&page=issues: Fatal error: Uncaught Error: Undefined class constant 'W_CURRENT' in \phpmyBugs\classes\Pager.class.php:41 Stack trace: #0 \phpmyBugs\pages\issues.php(144): Pager->get(Array, Object(Url), Array, 12) #1 \phpmyBugs\classes\Page.class.php(48): include('C:\\xampp\\htdocs...') #2 \phpmyBugs\index.php(382): Page->load('issues') #3 {main} thrown in \phpmyBugs\classes\Pager.class.php on line 41 with RU language.

**Comment by dineshkummarc** [comment]
done
