### ISSUE TITLE
/phpmyBugs/index.php?project=default&page=issues: Fatal error: Uncaught Error: Undefined class constant 'F_FILTER_STATES' in \phpmyBugs\pages\issues.php:204 Stack trace: #0 \phpmyBugs\classes\Page.class.php(48): include() #1 \phpmyBugs\index.php(382): Page->load('issues') #2 {main} thrown in \phpmyBugs\pages\issues.php on line 204

### ISSUE THREAD

**Issue by dineshkummarc** [dineshkummarc/phpmyBugs#44]
/phpmyBugs/index.php?project=default&page=issues: Fatal error: Uncaught Error: Undefined class constant 'F_FILTER_STATES' in \phpmyBugs\pages\issues.php:204 Stack trace: #0 \phpmyBugs\classes\Page.class.php(48): include() #1 \phpmyBugs\index.php(382): Page->load('issues') #2 {main} thrown in \phpmyBugs\pages\issues.php on line 204

**Comment by dineshkummarc** [comment]
done
