### ISSUE TITLE
/phpmyBugs/index.php?page=settings: Fatal error: Uncaught Error: Cannot declare self-referencing constant 'E_DEPRECated' in \phpmyBugs\languages\Trad_hindi.class.php:454 Stack trace: #0 \phpmyBugs\classes\Text.class.php(367): Trad::errors(8) #1 \phpmyBugs\languages\Trad_hindi.class.php(425): Text::capture_error(8, 'Use of undefine...', 'C:\\xampp\\htdocs...', 425, Array) #2 \phpmyBugs\pages\settings.php(296): Trad::permissions('home', 'title') #3 \phpmyBugs\classes\Page.class.php(48): include('C:\\xampp\\htdocs...') #4 \phpmyBugs\index.php(382): Page->load('settings') #5 {main} thrown in \phpmyBugs\languages\Trad_hindi.class.php on line 454

### ISSUE THREAD

**Issue by dineshkummarc** [dineshkummarc/phpmyBugs#45]
/phpmyBugs/index.php?page=settings: Fatal error: Uncaught Error: Cannot declare self-referencing constant 'E_DEPRECated' in \phpmyBugs\languages\Trad_hindi.class.php:454 Stack trace: #0 \phpmyBugs\classes\Text.class.php(367): Trad::errors(8) #1 \phpmyBugs\languages\Trad_hindi.class.php(425): Text::capture_error(8, 'Use of undefine...', 'C:\\xampp\\htdocs...', 425, Array) #2 \phpmyBugs\pages\settings.php(296): Trad::permissions('home', 'title') #3 \phpmyBugs\classes\Page.class.php(48): include('C:\\xampp\\htdocs...') #4 \phpmyBugs\index.php(382): Page->load('settings') #5 {main} thrown in \phpmyBugs\languages\Trad_hindi.class.php on line 454

**Comment by dineshkummarc** [comment]
done
